#----------------------------
#GitHub Action JavaLab3 For DevOps Lab 2
#
#----------------------------
name: DevOps_Lab2

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Compile Java application
      run: javac src/ValidData.java src/DateValidCheck.java src/People.java src/Main.java
      
    - name: Run Java application
      run: java -cp src Main "Чайкин Георгий Максимович 01.05.2023"
      
  Docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Compile Java application
      run: javac src/ValidData.java src/DateValidCheck.java src/People.java src/Main.java

    - name: Build Docker image
      run: |
          docker build -t my-pipeline-image .
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag my-pipeline-image ${{ secrets.DOCKERHUB_USERNAME }}/my-pipeline-image:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-pipeline-image:latest

    - name: Run Java application
      run: java -cp src Main "Чайкин Георгий Максимович 01.05.2023"
      








    
  
  
